spring.datasource.url=${DB_URL}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

management.health.db.enabled=true
management.health.redis.enabled=false

logging.level.dev.langchain4j=INFO
logging.level.com.example.demo=INFO
